name: twilio_programmable_voice
description: Non-official Flutter Twilio API for Twilio Programmable Voice Resource
version: 0.0.0-dev.1
homepage:
repository: https://github.com/Bilik-fr/twilio_programmable_voice/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^8.1.4+1 # https://pub.dev/packages/permission_handler
  soundpool: ^2.1.0
  hive_flutter: ^1.1.0
  background_fetch: ^1.0.1
  jwt_decoder: ^2.0.1
  firebase_messaging: ^10.0.4
  firebase_core : ^1.4.0
  dio: ^4.0.0
  uuid: ^3.0.4
  get_it: ^7.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  mockito: ^5.0.12
  http_mock_adapter: ^0.3.1

flutter:
  plugin:
    platforms:
      android:
        package: fr.izio.twilio_programmable_voice
        pluginClass: TwilioProgrammableVoicePlugin
      ios:
        pluginClass: SwiftTwilioProgrammableVoicePlugin
  assets:
    - packages/twilio_programmable_voice/assets/sounds/disconnect.wav
    - packages/twilio_programmable_voice/assets/sounds/incoming.wav
    - packages/twilio_programmable_voice/assets/sounds/outgoing.wav
